[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MLX90614 Library@^2.1.5
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DST7735_BLACKTAB
    -DTFT_MISO=-1
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=2
    -DTFT_RST=4
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=27000000

[env:test_sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MLX90614 Library@^2.1.5
build_src_filter = -<*> +<../test/test_sensor.cpp>

[env:test_display]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DST7735_BLACKTAB
    -DTFT_MISO=-1
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=2
    -DTFT_RST=4
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=27000000
build_src_filter = -<*> +<../test/test_display.cpp>

[env:test_relay]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test/test_relay.cpp>